/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package alvaroycarlos.basedatos;

import java.util.List;
import java.sql.Connection;
import java.sql.DatabaseMetaData;
import java.sql.DriverManager;
import java.sql.ResultSet;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;


/**
 *
 * @author PCNUEVO
 */
public class baseDatos extends javax.swing.JFrame {

    /**
     * Creates new form baseDatos
     */
    
    DefaultListModel modelo = new DefaultListModel();
    
    private String usuario;
    private char[] contraseña;
    
    private boolean verInfo = false;
    
    List<String> seleccion = null;
    
    public baseDatos() {
        
        initComponents();
        
        ocultarInterfaz();
        
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        
        list.setModel(modelo);
    }
    
    private void ocultarInterfaz(){
        verInfoBoton.setVisible(false);
        jScrollPane1.setVisible(false);
        jScrollPane1.setVisible(false);
        jLabel6.setVisible(false);
        simpleBoton.setVisible(false);
        intervaloBoton.setVisible(false);
        multipleBoton.setVisible(false);
        verInfoBoton.setVisible(false);
        limpiarBoton.setVisible(false);
        tablasBoton.setVisible(false);
        jLabel4.setVisible(false);
        
        seleccion = null;
        
        modelo.removeAllElements();
        
        usuario = "";
        char contraseña[] = {};
        
        tablasBoton.setSelected(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        datosGrupo = new javax.swing.ButtonGroup();
        selecionGrupo = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        usuarioCampo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        conectarseBoton = new javax.swing.JButton();
        conexionEstado = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        list = new javax.swing.JList<>();
        contraseñaCampo = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        simpleBoton = new javax.swing.JToggleButton();
        intervaloBoton = new javax.swing.JToggleButton();
        multipleBoton = new javax.swing.JToggleButton();
        verInfoBoton = new javax.swing.JToggleButton();
        limpiarBoton = new javax.swing.JToggleButton();
        tablasBoton = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Usuario: ");

        jLabel2.setText("Contraseña:");

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel3.setText("Inicia sesión");

        conectarseBoton.setText("Conectarse");
        conectarseBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                conectarseBotonActionPerformed(evt);
            }
        });

        conexionEstado.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        conexionEstado.setText("DESCONECTADO");

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel6.setText("Modo de selección ");

        jSeparator1.setForeground(new java.awt.Color(102, 204, 255));

        list.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(list);

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel4.setText("Datos");

        selecionGrupo.add(simpleBoton);
        simpleBoton.setSelected(true);
        simpleBoton.setText("Simple");
        simpleBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpleBotonActionPerformed(evt);
            }
        });

        selecionGrupo.add(intervaloBoton);
        intervaloBoton.setText("Intervalo");
        intervaloBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                intervaloBotonActionPerformed(evt);
            }
        });

        selecionGrupo.add(multipleBoton);
        multipleBoton.setText("Múltiples intervalos");
        multipleBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multipleBotonActionPerformed(evt);
            }
        });

        datosGrupo.add(verInfoBoton);
        verInfoBoton.setText("Ver selección");
        verInfoBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verInfoBotonActionPerformed(evt);
            }
        });

        datosGrupo.add(limpiarBoton);
        limpiarBoton.setText("Limpiar selección");
        limpiarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiarBotonActionPerformed(evt);
            }
        });

        datosGrupo.add(tablasBoton);
        tablasBoton.setSelected(true);
        tablasBoton.setText("Ver tablas");
        tablasBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tablasBotonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(usuarioCampo, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(contraseñaCampo, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(35, 35, 35)
                                .addComponent(conectarseBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(conexionEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(78, 78, 78)
                                                .addComponent(jLabel6))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(28, 28, 28)
                                                .addComponent(simpleBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(intervaloBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(jLabel4)
                                                .addGap(104, 104, 104))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(tablasBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                        .addComponent(verInfoBoton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(limpiarBoton, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(multipleBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 457, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 19, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(305, 305, 305))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3)
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(usuarioCampo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(contraseñaCampo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(simpleBoton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(intervaloBoton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(multipleBoton)
                                .addGap(37, 37, 37)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(verInfoBoton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(limpiarBoton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tablasBoton))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(conexionEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(conectarseBoton))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void conectarseBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_conectarseBotonActionPerformed
        usuario = usuarioCampo.getText();
        contraseña = contraseñaCampo.getPassword();
        if(usuario.equals("") || contraseña.equals("")){
            //MOSTRAR ERROR
            JOptionPane.showMessageDialog(this, "Ninguno de los campos puede quedar vacío", "Error en los datos", JOptionPane.ERROR_MESSAGE);  
            ocultarInterfaz();
            return;
        }
        String error = conectarBD(usuario, String.valueOf(contraseña));
        
        if(error.equals("")){
            //Conexion establecida
            conexionEstado.setText("CONECTADO");
            verInfoBoton.setVisible(true);
            jScrollPane1.setVisible(true);
            jLabel6.setVisible(true);
            simpleBoton.setVisible(true);
            intervaloBoton.setVisible(true);
            multipleBoton.setVisible(true);
            verInfoBoton.setVisible(true);
            limpiarBoton.setVisible(true);
            tablasBoton.setVisible(true);
            jLabel4.setVisible(true);
        }else{
            //mostrar error de conexion
            JOptionPane.showMessageDialog(this, "Error en la conexión a la base de datos", "Fallo de conexión", JOptionPane.ERROR_MESSAGE);  
            ocultarInterfaz();
        }
    }//GEN-LAST:event_conectarseBotonActionPerformed

    private void simpleBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpleBotonActionPerformed
        list.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        System.out.println("Simple");
    }//GEN-LAST:event_simpleBotonActionPerformed

    private void intervaloBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_intervaloBotonActionPerformed
        list.setSelectionMode(ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        System.out.println("intervalo");
    }//GEN-LAST:event_intervaloBotonActionPerformed

    private void multipleBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multipleBotonActionPerformed
        list.setSelectionMode(ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        System.out.println("Multiple");
    }//GEN-LAST:event_multipleBotonActionPerformed

    private void limpiarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiarBotonActionPerformed
        if(list.getSelectedIndices().length == 0){
            limpiarBoton.setSelected(false);
            return;
        }
        list.clearSelection();
    }//GEN-LAST:event_limpiarBotonActionPerformed

    private void verInfoBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verInfoBotonActionPerformed
        if(list.getSelectedIndices().length == 0){
            tablasBoton.setSelected(true);
            return;
        }
        seleccion = list.getSelectedValuesList();
        modelo.removeAllElements();
        conectarBD(usuario, String.valueOf(contraseña));
    }//GEN-LAST:event_verInfoBotonActionPerformed

    private void tablasBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tablasBotonActionPerformed
        seleccion = null;
        modelo.removeAllElements();
        conectarBD(usuario, String.valueOf(contraseña));
    }//GEN-LAST:event_tablasBotonActionPerformed

    public String conectarBD(String usuario, String contraseña){
        //Si la String devuelta está vacía significará que fue todo correcto,
        //si devuelve algo, será un error
        String error = "";
        try{
            //System.out.println("Usuario: " + usuario + " y contraseña: " + String.valueOf(contraseña));
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://i7-lab5.dis.ulpgc.es/DIU_BD?useSSL=true",usuario,String.valueOf(contraseña));
            //System.out.println("Mensaje de conexion: " + con.toString());
            DatabaseMetaData md = con.getMetaData();
            String[] types = {"TABLE"};
            ResultSet rs = md.getTables(null, null, "%", types);
            while (rs.next()) {
                String tabla = rs.getString("TABLE_NAME");
                if(seleccion == null){
                    modelo.addElement(tabla);
                }else{
                    //System.out.println("Tabla: " + tabla);
                    if(seleccion.contains(tabla)){
                        ResultSet rs2 = md.getColumns(null, null, tabla, null);
                        while (rs2.next()) {
                            String columna = rs2.getString("COLUMN_NAME");
                            modelo.addElement(tabla + "." + columna);
                            //System.out.println(" Campo: " + columna);
                        }
                    }
                }
                
            }
            con.close();
        }catch(Exception e){
            error = e.getMessage();
            System.out.println("Mensaje de error: "+ error);
        }
        return error;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(baseDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(baseDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(baseDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(baseDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new baseDatos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton conectarseBoton;
    private javax.swing.JLabel conexionEstado;
    private javax.swing.JPasswordField contraseñaCampo;
    private javax.swing.ButtonGroup datosGrupo;
    private javax.swing.JToggleButton intervaloBoton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JToggleButton limpiarBoton;
    private javax.swing.JList<String> list;
    private javax.swing.JToggleButton multipleBoton;
    private javax.swing.ButtonGroup selecionGrupo;
    private javax.swing.JToggleButton simpleBoton;
    private javax.swing.JToggleButton tablasBoton;
    private javax.swing.JTextField usuarioCampo;
    private javax.swing.JToggleButton verInfoBoton;
    // End of variables declaration//GEN-END:variables
}
